version: '3.4'
services:
  redis-sentinel0:
    container_name: redis-sentinel0
    build: 
        context: redis
        args:
          - REDIS_PORT=26379
          - REDIS_MASTER_HOST=172.19.0.4
          - REDIS_MASTER_PORT=9001
    volumes: 
        - ./redis-shard/redis-sentinel0:/data
    ports: 
      - 26379:26379
    networks:
      - redis-net

  redis-sentinel1:
    container_name: redis-sentinel1
    build: 
        context: redis
        args:
          - REDIS_PORT=26380
          - REDIS_MASTER_HOST=172.19.0.4
          - REDIS_MASTER_PORT=9001
    volumes: 
        - ./redis-shard/redis-sentinel1:/data
    ports: 
      - 26380:26380
    networks:
      - redis-net

  redis-sentinel2:
    container_name: redis-sentinel2
    build: 
        context: redis
        args:
          - REDIS_PORT=26381
          - REDIS_MASTER_HOST=172.19.0.4
          - REDIS_MASTER_PORT=9001
    volumes: 
        - ./redis-shard/redis-sentinel2:/data
    ports: 
      - 26381:26381
    networks:
      - redis-net

networks:
  redis-net:
    name: redis-scaling-network
